version: 2
cache_key: &cache_key
  key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

general:
jobs:
  build:
    working_directory: ~/TourReview
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
         <<: *cache_key

      - run:
          name: Assemble
          command: ./gradlew assemble
      - store_artifacts:
          path: artifacts/android/build/outputs/
      - store_artifacts:
          path: build/commit-timestamp.txt

      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"

      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Run Lint Tests
          command: ./gradlew lintDebug
      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest
      ##- run:
         ## name: Run Instrumented Test (DEV)
         ## command: ./gradlew connectedDEVAndroidTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.gradle/caches
            - ~/.gradle/wrapper
          <<: *cache_key

workflows:
  version: 2
  build_and_test:
    jobs:
      - build